## list of guild data
guilds: # <guild[]>
  # guild id
  - id: # <string>
    # channel to log in
    log_channel: # <string>
    # threshold to use as fallback
    attribute_threshold: # [number] # defaults on the more specific flag attributes
    # list of attributes that should be considered severe (level 3)
    severe_attributes: # <attribute[]>
      # attribute flag
      - key: # <string>
        # threshold for this attribute to be considered severe
        threshold: # [number] # default: attribute_threshold -> 0
    # amount of severe attributes to log as level severe (level 3)
    severe_amount: # [number] # default: 1
    # list of attributes that should be monitored
    monitor_attributes: # <attribute[]>
      # attribute flag
      - key: # <string>
        # threshold for this attribute to be monitored
        threshold: # [number] # default: attribute_threshold -> 0
    # threshold for an attribute hit to be considered high
    high_threshold: # [number] # default: 0
    # amount of high attributes to log as level alert (level 2)
    high_amount: # [number] # default: 1
    # threshold for attributes to trigger a log
    log_threshold: # [number] # default: 8
    # amount of attributes hit at log_threshold to trigger a log
    log_amount: # [number] # default: 0
    # list of channel to monitor
    monitor_channels: # <string[]>
    # notification settings
    notifications:
      # role ids that should be notified
      roles: # [string[]] # default: []
      # user ids that should be notified
      users: # [string[]] # default: []
      # level threshold to cause a notification
      level: # [number] # default: 0
      # string to prefix the notifications with
      prefix: # [string] # default: ''
