version: '3'

services:
  application:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
  database:
    image: postgres
    restart: always
    env_file:
      - ./database.env
    volumes:
      - ./postgres_data:/var/lib/postgresql:rw
    ports:
      - '8001:5432'
  redis:
    image: redis:alpine
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis-volume:/data
    expose:
      - '6379'
