version: '3'

services:
  application:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
  redis:
    image: redis:alpine
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis-volume:/data
    expose:
      - '6379'

  redis-exporter:
    image: oliver006/redis_exporter:alpine
    environment:
      REDIS_ADDR: 'redis://redis:6379'
      REDIS_EXPORTER_CHECK_KEYS: 'db0=*messages:*,db0=*attributes:seen*'
    expose:
      - '9121'
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    environment:
      GF_DEFAULT_INSTANCE_NAME: ''
      GF_SECURITY_ADMIN_USER: ''
      GF_SECURITY_ADMIN_PASSWORD: ''
      GF_AUTH_ANONYMOUS_ENABLED: ''
      GF_ANALYTICS_REPORTING_ENABLED: 'false'
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-piechart-panel,redis-datasource'
    expose:
      - '3000'
    ports:
      - '127.0.0.1:3000:3000'
    restart: unless-stopped
    volumes:
      - ./grafana-data:/grafana

  prometheus:
    build: ./docker/prometheus
    volumes:
      - ./prometheus-data:/prometheus
    expose:
      - '9090'
    restart: unless-stopped
