version: '3'

services:
  application:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
  redis:
    image: redis:alpine
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis-volume:/data
