{
 "title": "Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Rate messages checked and seen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_key_value{key=~\".*messages:checked.*\"} [$__rate_interval]))",
     "legendFormat": "messages checked"
    },
    {
     "expr": "sum(rate(redis_key_value{key=~\".*messages:seen.*\"} [$__rate_interval]))",
     "legendFormat": "messages seen"
    }
   ]
  },
  {
   "title": "Discord.js totals",
   "type": "graph",
   "description": "Total attributes observed on discord.js over time",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_key_value{key=~\".*222078108977594368:attribute.*\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Total messages checked and seen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_key_value{key=~\".*messages:checked.*\"})",
     "legendFormat": "messages checked"
    },
    {
     "expr": "sum(redis_key_value{key=~\".*messages:seen.*\"})",
     "legendFormat": "messages seen"
    }
   ]
  }
 ]
}