global:
  scrape_interval: 5s
  evaluation_interval: 5s
  # scrape_timeout is set to the global default (10s).

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'redis'
    static_configs:
      - targets:
          - 'redis-exporter:9121'
