theme: jekyll-theme-cayman
title: Project Sentinel
description: Imagine a bot... that allows your moderators to focus on investigation, compassion, and situational awareness by finding and flagging toxicity and conversational attributes.
